version: '3'

services:
  web:
    container_name: 'webapp'
    image: 'webapp'
    build:
      context: .
      dockerfile: webapp.dockerfile
    volumes:
      - .:/app
    ports:
     - "5000:5000"
    networks:
      - workable-network

networks:
  workable-network:
    driver: bridge  